# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmE1NTJkZjU0ODhiNGJmMWNiNmFmZmFhMmI1NDYxNWM2OTA4YjI2YmVkNDAyZWUxYjUyM2I1NTk2ZjcwY2IxNGUxZDM5NDY0ZjQ5M2EyMjY5YzZjYjA5NTM5NDBjZTk0MGQ3ZTAxZTEzOGJlMGY5ZmM1OGEzYmU5YzgyMTQ0N2Q=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
